import { Injectable } from '@angular/core';
import { Observable, of } from 'rxjs';

@Injectable({
  providedIn: 'root',
})
export class GuestService {
  private guestModeKey = 'guest_mode';

  constructor() {}

  enableGuestMode() {
    localStorage.setItem(this.guestModeKey, 'true');
  }

  disableGuestMode() {
    localStorage.removeItem(this.guestModeKey);
  }

  isGuestMode(): boolean {
    return localStorage.getItem(this.guestModeKey) === 'true';
  }

  getWorkouts(): Observable<any> {
    return of([
      {
        id: 1,
        name: '3-Day Split Workout',
        icon: 1,
        workoutPerDays: [
          {
            id: 1,
            date: '2025-03-04',
            dayOfWeek: 'TUESDAY',
            workoutId: 1,
            exercises: [
              {
                id: 1,
                name: 'Lat Pulldown',
                sets: 4,
                reps: 12,
                weight: 70.0,
                rir: 2,
                completed: false,
                workoutPerDayId: 1,
                muscleGroup: 'BACK',
              },
              {
                id: 2,
                name: 'Seated Row',
                sets: 4,
                reps: 10,
                weight: 80.0,
                rir: 1,
                completed: false,
                workoutPerDayId: 1,
                muscleGroup: 'BACK',
              },
              {
                id: 3,
                name: 'Deadlift',
                sets: 4,
                reps: 8,
                weight: 120.0,
                rir: 2,
                completed: false,
                workoutPerDayId: 1,
                muscleGroup: 'BACK',
              },
            ],
          },
          {
            id: 2,
            date: '2025-03-05',
            dayOfWeek: 'WEDNESDAY',
            workoutId: 1,
            exercises: [
              {
                id: 4,
                name: 'Bench Press',
                sets: 4,
                reps: 8,
                weight: 90.0,
                rir: 2,
                completed: false,
                workoutPerDayId: 2,
                muscleGroup: 'CHEST',
              },
              {
                id: 5,
                name: 'Incline Dumbbell Press',
                sets: 3,
                reps: 10,
                weight: 30.0,
                rir: 1,
                completed: false,
                workoutPerDayId: 2,
                muscleGroup: 'CHEST',
              },
              {
                id: 6,
                name: 'Cable Flyes',
                sets: 3,
                reps: 12,
                weight: 15.0,
                rir: 1,
                completed: false,
                workoutPerDayId: 2,
                muscleGroup: 'CHEST',
              },
            ],
          },
          {
            id: 3,
            date: '2025-03-06',
            dayOfWeek: 'THURSDAY',
            workoutId: 1,
            exercises: [
              {
                id: 7,
                name: 'Overhead Press',
                sets: 3,
                reps: 8,
                weight: 50.0,
                rir: 2,
                completed: false,
                workoutPerDayId: 3,
                muscleGroup: 'SHOULDERS',
              },
              {
                id: 8,
                name: 'Lateral Raises',
                sets: 3,
                reps: 12,
                weight: 12.5,
                rir: 1,
                completed: false,
                workoutPerDayId: 3,
                muscleGroup: 'SHOULDERS',
              },
              {
                id: 9,
                name: 'Face Pulls',
                sets: 3,
                reps: 15,
                weight: 25.0,
                rir: 2,
                completed: false,
                workoutPerDayId: 3,
                muscleGroup: 'SHOULDERS',
              },
            ],
          },
          {
            id: 4,
            date: '2025-03-11',
            dayOfWeek: 'TUESDAY',
            workoutId: 1,
            exercises: [
              {
                id: 10,
                name: 'Barbell Row',
                sets: 4,
                reps: 10,
                weight: 75.0,
                rir: 2,
                completed: false,
                workoutPerDayId: 4,
                muscleGroup: 'BACK',
              },
              {
                id: 11,
                name: 'Pull-ups',
                sets: 4,
                reps: 8,
                weight: 0.0,
                rir: 1,
                completed: false,
                workoutPerDayId: 4,
                muscleGroup: 'BACK',
              },
              {
                id: 12,
                name: 'Single-Arm Dumbbell Row',
                sets: 4,
                reps: 12,
                weight: 25.0,
                rir: 1,
                completed: false,
                workoutPerDayId: 4,
                muscleGroup: 'BACK',
              },
            ],
          },
          {
            id: 5,
            date: '2025-03-12',
            dayOfWeek: 'WEDNESDAY',
            workoutId: 1,
            exercises: [
              {
                id: 13,
                name: 'Dumbbell Bench Press',
                sets: 3,
                reps: 10,
                weight: 35.0,
                rir: 2,
                completed: false,
                workoutPerDayId: 5,
                muscleGroup: 'CHEST',
              },
              {
                id: 14,
                name: 'Push-ups',
                sets: 3,
                reps: 15,
                weight: 0.0,
                rir: 1,
                completed: false,
                workoutPerDayId: 5,
                muscleGroup: 'CHEST',
              },
              {
                id: 15,
                name: 'Decline Bench Press',
                sets: 3,
                reps: 8,
                weight: 75.0,
                rir: 2,
                completed: false,
                workoutPerDayId: 5,
                muscleGroup: 'CHEST',
              },
            ],
          },
          {
            id: 6,
            date: '2025-03-13',
            dayOfWeek: 'THURSDAY',
            workoutId: 1,
            exercises: [
              {
                id: 16,
                name: 'Arnold Press',
                sets: 3,
                reps: 10,
                weight: 20.0,
                rir: 2,
                completed: false,
                workoutPerDayId: 6,
                muscleGroup: 'SHOULDERS',
              },
              {
                id: 17,
                name: 'Upright Rows',
                sets: 3,
                reps: 12,
                weight: 30.0,
                rir: 1,
                completed: false,
                workoutPerDayId: 6,
                muscleGroup: 'SHOULDERS',
              },
              {
                id: 18,
                name: 'Rear Delt Flyes',
                sets: 3,
                reps: 15,
                weight: 10.0,
                rir: 1,
                completed: false,
                workoutPerDayId: 6,
                muscleGroup: 'SHOULDERS',
              },
            ],
          },
          {
            id: 7,
            date: '2025-03-18',
            dayOfWeek: 'TUESDAY',
            workoutId: 1,
            exercises: [
              {
                id: 19,
                name: 'T-Bar Row',
                sets: 4,
                reps: 10,
                weight: 60.0,
                rir: 2,
                completed: false,
                workoutPerDayId: 7,
                muscleGroup: 'BACK',
              },
              {
                id: 20,
                name: 'Chin-ups',
                sets: 4,
                reps: 8,
                weight: 0.0,
                rir: 1,
                completed: false,
                workoutPerDayId: 7,
                muscleGroup: 'BACK',
              },
              {
                id: 21,
                name: 'Cable Rows',
                sets: 4,
                reps: 12,
                weight: 65.0,
                rir: 1,
                completed: false,
                workoutPerDayId: 7,
                muscleGroup: 'BACK',
              },
            ],
          },
          {
            id: 8,
            date: '2025-03-19',
            dayOfWeek: 'WEDNESDAY',
            workoutId: 1,
            exercises: [
              {
                id: 22,
                name: 'Incline Bench Press',
                sets: 3,
                reps: 8,
                weight: 75.0,
                rir: 2,
                completed: false,
                workoutPerDayId: 8,
                muscleGroup: 'CHEST',
              },
              {
                id: 23,
                name: 'Dumbbell Flyes',
                sets: 3,
                reps: 12,
                weight: 17.5,
                rir: 1,
                completed: false,
                workoutPerDayId: 8,
                muscleGroup: 'CHEST',
              },
              {
                id: 24,
                name: 'Chest Dips',
                sets: 3,
                reps: 10,
                weight: 0.0,
                rir: 1,
                completed: false,
                workoutPerDayId: 8,
                muscleGroup: 'CHEST',
              },
            ],
          },
          {
            id: 9,
            date: '2025-03-20',
            dayOfWeek: 'THURSDAY',
            workoutId: 1,
            exercises: [
              {
                id: 25,
                name: 'Seated Dumbbell Press',
                sets: 4,
                reps: 8,
                weight: 22.5,
                rir: 2,
                completed: false,
                workoutPerDayId: 9,
                muscleGroup: 'SHOULDERS',
              },
              {
                id: 26,
                name: 'Front Raises',
                sets: 3,
                reps: 12,
                weight: 12.5,
                rir: 1,
                completed: false,
                workoutPerDayId: 9,
                muscleGroup: 'SHOULDERS',
              },
              {
                id: 27,
                name: 'Shrugs',
                sets: 3,
                reps: 15,
                weight: 35.0,
                rir: 1,
                completed: false,
                workoutPerDayId: 9,
                muscleGroup: 'SHOULDERS',
              },
            ],
          },
          {
            id: 10,
            date: '2025-03-25',
            dayOfWeek: 'TUESDAY',
            workoutId: 1,
            exercises: [
              {
                id: 28,
                name: 'Deadlift',
                sets: 4,
                reps: 6,
                weight: 130.0,
                rir: 2,
                completed: false,
                workoutPerDayId: 10,
                muscleGroup: 'BACK',
              },
              {
                id: 29,
                name: 'Lat Pulldown',
                sets: 4,
                reps: 12,
                weight: 75.0,
                rir: 1,
                completed: false,
                workoutPerDayId: 10,
                muscleGroup: 'BACK',
              },
              {
                id: 30,
                name: 'Seated Row',
                sets: 3,
                reps: 10,
                weight: 85.0,
                rir: 1,
                completed: false,
                workoutPerDayId: 10,
                muscleGroup: 'BACK',
              },
            ],
          },
          {
            id: 11,
            date: '2025-03-26',
            dayOfWeek: 'WEDNESDAY',
            workoutId: 1,
            exercises: [
              {
                id: 31,
                name: 'Bench Press',
                sets: 3,
                reps: 6,
                weight: 95.0,
                rir: 2,
                completed: false,
                workoutPerDayId: 11,
                muscleGroup: 'CHEST',
              },
              {
                id: 32,
                name: 'Incline Dumbbell Press',
                sets: 3,
                reps: 10,
                weight: 32.5,
                rir: 1,
                completed: false,
                workoutPerDayId: 11,
                muscleGroup: 'CHEST',
              },
              {
                id: 33,
                name: 'Cable Crossovers',
                sets: 3,
                reps: 12,
                weight: 17.5,
                rir: 1,
                completed: false,
                workoutPerDayId: 11,
                muscleGroup: 'CHEST',
              },
            ],
          },
          {
            id: 12,
            date: '2025-03-27',
            dayOfWeek: 'THURSDAY',
            workoutId: 1,
            exercises: [
              {
                id: 34,
                name: 'Military Press',
                sets: 4,
                reps: 8,
                weight: 55.0,
                rir: 2,
                completed: false,
                workoutPerDayId: 12,
                muscleGroup: 'SHOULDERS',
              },
              {
                id: 35,
                name: 'Lateral Raises',
                sets: 4,
                reps: 12,
                weight: 15.0,
                rir: 1,
                completed: false,
                workoutPerDayId: 12,
                muscleGroup: 'SHOULDERS',
              },
              {
                id: 36,
                name: 'Reverse Pec Deck',
                sets: 4,
                reps: 15,
                weight: 27.5,
                rir: 1,
                completed: false,
                workoutPerDayId: 12,
                muscleGroup: 'SHOULDERS',
              },
            ],
          },
        ],
      },
    ]);
  }
}
